### Request to /traceroute endpoint
GET http://localhost:8090/traceroute?domain=google.com

### Request to /journey endpoint
GET http://localhost:8090/journey
Host: prothomalo.com
Content-Type: application/json

### Request to /health endpoint
GET http://localhost:8089/health